version: '3.4'

services:
  hello-atari:
    image: hello-atari
    build:
      context: ../nodeapp
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: sleep infinity
    volumes:
      - chia-ssl:/usr/src/chia-ssl
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:atari
    ports:
      - 8444:8444
    environment:
      - keys=generate
      - TZ=${TZ}
      # Enable UPnP
      - upnp=false
      # Enable log file generation
      - log_to_file=true
    volumes:
      - ~/.chia/mainnet/db:/root/.chia/mainnet/db
      - ~/.chia/mainnet/data_layer:/root/.chia/mainnet/data_layer
      - chia-ssl:/root/.chia/mainnet/config/ssl
volumes:
  chia-ssl:
