version: "3.7"
services:
  hello-atari:
    image: hello-atari
    build:
      context: nodeapp
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: sleep infinity
    volumes:
      - chia-ssl:/usr/src/chia-ssl
  chia:
    container_name: chia
    restart: unless-stopped
    image: ghcr.io/chia-network/chia:atari
    ports:
      - 8444:8444
      - 8561:8561
      - 8000:8000
    environment:
      - keys=persistent
      - upnp=false
      - log_to_file=true
      - service=node
    volumes:
      - ~/.chia-atari:/root/.chia
      - chia-ssl:/root/.chia/mainnet/config/ssl
volumes:
  chia-ssl: